apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-k8s-sistemas-126
  namespace: argocd
  labels:
    funpresp.io/ambiente: k8s-sistemas-126
spec:
  project: monitoring
  syncPolicy: { automated: { prune: true, selfHeal: true } }
  destination: { name: k8s-sistemas-126, namespace: monitoring, server: '' }
  source:
    repoURL: https://gitlab.funpresp.com.br/g-infraestrutura/g-kubernetes/gitops.git
    targetRevision: k8s-sistemas-126
    path: monitoring
    directory: { recurse: true }
