---
# ONLY for Mutual TLS
apiVersion: v1
kind: Secret
metadata:
  name: sidecar-tls
  namespace: monitoring
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDPzCCAuSgAwIBAgIUSlEKpBgjpjct/zEsfHG+UwXI948wCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDIwNTE4MjEwMFoXDTI1
    MDIwNDE4MjEwMFowXTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxLTArBgNVBAMTJHNpZGVjYXIubW9uaXRvcmluZy5zdmMuY2x1
    c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL0yVme0
    7/OqK3VnnofYjor267oUWmzU+UJQYUk5Qv2lOJFGrU6hflUoDJ5wDJQq3asRpXRT
    c7+l8FhTUb/7IJ83WCR1K4oUX3fUr/p/SgBKQ4XRs4ajjZZDxLGTrnmyzxDDh4wy
    AC506og1zb3AGoWZgtC6LVXM+zqxg/V5BE1ypoYrvOtOukzBOL8KUGjB0scHFA2X
    TwIoscIzig1wELjPCYRtlYT3q11tKtCI6NmmY0U1REanp3IxtBGkfoKawNRwfbCa
    R4Hmv8OKqcRgZ+soM2m7NeUhR44ThK3y8ar3Xa7Jpj0Bbi94RUviqk+0h66Qw3IY
    f0eLAXGn6mVO35sCAwEAAaOByTCBxjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
    FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFGQo
    OLsMBk9WgrUlyYENpeobz7ylMB8GA1UdIwQYMBaAFB/ohtKf6sHrlCH5qOvKyaUy
    kbaJMEcGA1UdEQRAMD6CJHNpZGVjYXIubW9uaXRvcmluZy5zdmMuY2x1c3Rlci5s
    b2NhbIIWc2lkZWNhci5hbnRvbnB1dHJhLmNvbTAKBggqhkjOPQQDAgNJADBGAiEA
    1FuUyUgjv1/vie9C1Nq4nfB0cq7IUtAKpVKA9wCP+MYCIQDXzJb2xOmIfXOh0Obb
    PLxgCX7aPQjYXkzh5irZqTqtrw==
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAvTJWZ7Tv86ordWeeh9iOivbruhRabNT5QlBhSTlC/aU4kUat
    TqF+VSgMnnAMlCrdqxGldFNzv6XwWFNRv/sgnzdYJHUrihRfd9Sv+n9KAEpDhdGz
    hqONlkPEsZOuebLPEMOHjDIALnTqiDXNvcAahZmC0LotVcz7OrGD9XkETXKmhiu8
    6066TME4vwpQaMHSxwcUDZdPAiixwjOKDXAQuM8JhG2VhPerXW0q0Ijo2aZjRTVE
    RqencjG0EaR+gprA1HB9sJpHgea/w4qpxGBn6ygzabs15SFHjhOErfLxqvddrsmm
    PQFuL3hFS+KqT7SHrpDDchh/R4sBcafqZU7fmwIDAQABAoIBAQCRUm/h+q3wqH33
    ER9I0wMyJFWOOYH3ZGMNF7aSSuR09YqMtA/8fLkP6dI/hGt1B7P6aXR/9HXM+EWz
    YlRBtUAqa5VNc5580gc+gOSm8UzDCkfxKtDNkyT3DZiwmXID0l+QTc/41JMlG/Ll
    qwYcQMleYzqC3u5hoDA8tgtY6ppubVbbielqIIH1I5E9HHsQgHowC4BEx0LA9w5p
    H1hy+UjF02olzTXT9nFpcCsxoUafSwMGYs3HzpGO7/BLkOhBfkJVwFnAWi65cgTz
    OdTfDqsq99IE40MbB6RevnFs8Zn62Mcn4PpXekDIXWjZAGSppNLl5A0YrC5Cyu7o
    smxg2qopAoGBANZDTfYgKuDZ/uI09yX6oh0emg/aI7FtSEUER3F40bLotv4JynvA
    a5j9EcdC3gOCobMWwHqjQdTdg1slIJsdcx4yezp3oXw8KlR8NhBZHfJTmJDa17wG
    Mu374ihDBppW1Gxcjbk9XVlyaYRNhPqv0Gw1P3VIIrHsTyajtm4G5A0/AoGBAOIN
    DCQ23fQeWNT42/jBQQ1GEDQ+EpTEZt0Zt5XKHVPn3Nl6JFndYipKA2qVJV6BLykt
    4eWKFyXRaOiSbzDr/qmAzVQaV5PbfZnHhbRfcCgcY8xBfZkNwoK7Nqys5cQUicgz
    kqNKtdqELiFl0cj7FQWtxmZFSx4AsLIwNDueWiqlAoGBAL58J5thDb3JEKjanb7O
    C8IHqr/dF05t8YoqO7nNx+BetBE1cyaB8yaYFm4oLGjCgi9NUuG0spokNNubLlm4
    3NdD2foo0RA6DQf/RbFTCSSe3UwqwxEOEckx3eYdcIlWGJQd1IGS5KLY7KYKpOaZ
    15nb3QbPksjLZbLcaRt4VNbRAoGAZfgSwQdLCgLieXek6spqSM2RI6/Ye+k4qYYf
    TV916VKPSj8RxMPbs03dyqdqyv2lQ4MiAoRPOs0C8N6Vb9EU+GtUtBqJ5PW+666Y
    PqxKkJ112z6zpGYTlxtSZ4Q6xT+qg3fYLvbVn7O+h2xBvNKeQgiIlbuuTeNr0YVz
    Gm2tKM0CgYAjcXltRM8V63LqKunUUy2K+m1N+ejH3/NSLhKJVe5+INz2Flh2Nl5L
    eG+nYIChPj9C1OqPOjfjngmkurL+KeUzgGoYes3hHifw1RyxAzuZmONl/9FHtciB
    tMcrZSY5WyExm1oXTBoLiPF275qidsAb+b50KFMaYJD1DYL7P8cBaA==
    -----END RSA PRIVATE KEY-----

  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUIhzF1VRv7yl5zqE6l5obNCRi1RgwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDIwNTE4MjAwMFoXDTI5
    MDIwMzE4MjAwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAE6/AXBU0u2Tn6/STgOxlieF4OelSB5W0zA0TiAMat
    gHqdvnnUq/hNxjROMqB7UE4YK5+n5kJjum714dlQ5QRAZaNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFB/ohtKf6sHrlCH5qOvK
    yaUykbaJMAoGCCqGSM49BAMCA0kAMEYCIQDqvqeTZ1lw6CVTj3csGoH7X1HBuHfK
    dBexDblGzcU1ugIhAK6Lmmqh2dbtKYYJLep2ayvutWjs/Eu+AD/sx3Gqs0Ab
    -----END CERTIFICATE-----

