---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-tls
  namespace: monitoring
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDTCCArOgAwIBAgIUB/fc3q2OL0UFLdh5/qwHnPRCzXAwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDIwNTIwMDQwMFoXDTI1
    MDIwNDIwMDQwMFowZDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxNDAyBgNVBAMTK3JlY2VpdmVyLXdyaXRlLm1vbml0b3Jpbmcu
    c3ZjLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASL2pab
    g7xkGpXCIfFt2THZM7tRJaq/PekXvuU5w4FjORrn4dxqlMsAY1Rp/nvfHPPTvIuG
    9Qa+HzcrkRIPTkSjo4IBWzCCAVcwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQG
    CCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRM0ckM
    IQNhih4usXOMauG/jAa//DAfBgNVHSMEGDAWgBQf6IbSn+rB65Qh+ajrysmlMpG2
    iTCB1wYDVR0RBIHPMIHMgityZWNlaXZlci13cml0ZS5tb25pdG9yaW5nLnN2Yy5j
    bHVzdGVyLmxvY2FsgjNyZWNlaXZlci1zdG9yZS0xLm1vbml0b3Jpbmcuc3ZjLmNs
    dXN0ZXIubG9jYWw6MTA5MDeCM3JlY2VpdmVyLXN0b3JlLTIubW9uaXRvcmluZy5z
    dmMuY2x1c3Rlci5sb2NhbDoxMDkwN4IzcmVjZWl2ZXItc3RvcmUtMy5tb25pdG9y
    aW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjEwOTA3MAoGCCqGSM49BAMCA0gAMEUCIQDV
    hZM/kUFYEkAFqakIMfSq93GXfJCzN6tizdgNGxCsGgIgR5PbBYffx2NSVGDOGJhT
    k5KyauRJhg/bA4cnKFZq5ng=
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIAJbJqoqkOvpuZQtGnE2BcmNSO1nGhv1TyRJBbLwhKeJoAoGCCqGSM49
    AwEHoUQDQgAEi9qWm4O8ZBqVwiHxbdkx2TO7USWqvz3pF77lOcOBYzka5+HcapTL
    AGNUaf573xzz07yLhvUGvh83K5ESD05Eow==
    -----END EC PRIVATE KEY-----

  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUIhzF1VRv7yl5zqE6l5obNCRi1RgwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDIwNTE4MjAwMFoXDTI5
    MDIwMzE4MjAwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAE6/AXBU0u2Tn6/STgOxlieF4OelSB5W0zA0TiAMat
    gHqdvnnUq/hNxjROMqB7UE4YK5+n5kJjum714dlQ5QRAZaNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFB/ohtKf6sHrlCH5qOvK
    yaUykbaJMAoGCCqGSM49BAMCA0kAMEYCIQDqvqeTZ1lw6CVTj3csGoH7X1HBuHfK
    dBexDblGzcU1ugIhAK6Lmmqh2dbtKYYJLep2ayvutWjs/Eu+AD/sx3Gqs0Ab
    -----END CERTIFICATE-----

